version: '3'
services:
  pizzeriaRemoloApiRest:
    image: pizzeria-remolo-api-image:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker:3307/pizzeriadonromulo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.MySQL8Dialect
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: pizzeria-remolo-api-container
    depends_on:
      - mysql-docker
  mysql-docker:
    image: 'mysql:8.0.27'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=pizzeriadonromulo
      - MYSQL_TCP_PORT=3307
    ports:
      - 3308:3307
    security_opt:
      - seccomp:unconfined
